# Generated by Django 3.2.5 on 2021-07-13 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                ("target", models.CharField(max_length=256, verbose_name="target")),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "Open"),
                            (2, "Assigned"),
                            (3, "Completed"),
                            (4, "Failed"),
                        ],
                        default=1,
                        protected=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "hitman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="hitman",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hit",
                "verbose_name_plural": "Hits",
            },
        ),
    ]
