# Generated by Django 3.2.5 on 2021-07-14 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hit",
            options={
                "ordering": ("-pk",),
                "verbose_name": "Hit",
                "verbose_name_plural": "Hits",
            },
        ),
        migrations.RemoveField(
            model_name="hit",
            name="hitman",
        ),
        migrations.AddField(
            model_name="hit",
            name="assignee",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hitman",
                to="authentication.user",
                verbose_name="hitman",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hit",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="manager",
                to="authentication.user",
                verbose_name="creator",
            ),
            preserve_default=False,
        ),
    ]
