# Generated by Django 3.2.5 on 2021-07-14 06:19

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_auto_20210713_1926"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[(1, "ACTIVE"), (2, "INACTIVE")],
                default=1,
                protected=True,
                verbose_name="Status",
            ),
        ),
    ]
