# Generated by Django 3.2.5 on 2021-07-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_user_group_hitmans"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="group_hitmans",
        ),
        migrations.AddField(
            model_name="user",
            name="managers",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="authentication.user",
                verbose_name="Jefe",
            ),
            preserve_default=False,
        ),
    ]
