# Generated by Django 3.2.5 on 2021-07-14 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_auto_20210714_1114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="managers",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Jefe",
            ),
        ),
    ]
